// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config'

export default defineConfig({
  datasource: {
    url: 'postgresql://lucio:senha123@localhost:5432/tasks_db',
  },
})